# Generated by Django 3.0.5 on 2020-07-23 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Clocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='none/no-img.jpg', null=True, upload_to='clocking')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_idd', models.CharField(max_length=5)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('Type', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=255)),
                ('imgprofile', models.ImageField(default='none/no-img.jpg', null=True, upload_to='employee')),
                ('imgstraight', models.ImageField(default='none/no-img.jpg', null=True, upload_to='employee')),
                ('imgtop', models.ImageField(default='none/no-img.jpg', null=True, upload_to='employee')),
                ('imgbottom', models.ImageField(default='none/no-img.jpg', null=True, upload_to='employee')),
                ('imgleft', models.ImageField(default='none/no-img.jpg', null=True, upload_to='employee')),
                ('imgright', models.ImageField(default='none/no-img.jpg', null=True, upload_to='employee')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceweb.Status')),
            ],
        ),
        migrations.CreateModel(
            name='Clocking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door', models.CharField(max_length=5)),
                ('temp', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('datetime', models.DateTimeField()),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faceweb.Employee')),
            ],
        ),
    ]
